### ISSUE TITLE
1.0.0

### ISSUE THREAD

**Issue by Mothblocks** [tgstation/rust-g#100]
I know it doesn't mean much in a context like this, but rust-g has been battle tested in many major servers and likely will not receive many backwards incompatible changes for a bit. Would be nice to move to 1.0.0 to better communicate what is happening in the updates.

**Comment by optimumtact** [comment]
ok

**Comment by ZeWaka** [comment]
will move to 1.0.0 after 0.8.0, as an empty no changes release
