### ISSUE TITLE
dmi_strip_metadata leads to removing alpha channel from the icon

### ISSUE THREAD

**Issue by DTraitor** [tgstation/rust-g#135]
`dmi_strip_metadata` leads to removing alpha channel from the icon
Here is the code I used:
```js
/world
	fps = 25
	icon_size = 32
	view = 6

/mob/Login()
 	var/icon/test = icon('twitcher.dmi', "preview")
	fcopy(test, "temp.png")
	client << browse_rsc(icon("temp.png"), "first.png")
	call("rust_g", "dmi_strip_metadata")("temp.png")
	сlient << browse_rsc(icon("temp.png"), "second.png")
```
`twitcher.dmi`: https://cdn.discordapp.com/attachments/693217263934898190/1111983453760651324/twitcher.dmi

Code result:
`first.png`:
![first](https://github.com/tgstation/rust-g/assets/74188902/42b5ba35-8af2-4e1f-a423-8dc941523eb7)
`second.png`:
![second](https://github.com/tgstation/rust-g/assets/74188902/b206c31d-c9c6-492f-b7ec-bbfa5c92684f)

**Comment by AnturK** [comment]
Yeah, not copying tRNS chunk from the original.
