### ISSUE TITLE
rustg_file_exists() returns "false" instead of "" if the file is not found

### ISSUE THREAD

**Issue by Kapu1178** [tgstation/rust-g#153]
Rustg methods that replace byond methods should behave identically or only expand on the behavior of the byond method. A github code search of "rustg_file_exists" shows that every single user of this method thinks it returns a truthy or falsey value. However, this is not the case.

**Comment by ZeWaka** [comment]
It's not obvious and you should say why

**Comment by Kapu1178** [comment]
> It's not obvious and you should say why

post updated
