### ISSUE TITLE
Dependencies are not handled.

### ISSUE THREAD

**Issue by MrStonedOne** [tgstation/rust-g#4]
System level dependencies are not handled by the cargo file and are not indexed or listed anywhere.

**Comment by MrStonedOne** [comment]
This, by the way, is the reason I fucking hate libraries and language level package managers.

They never handle this, they obfuscate this, if you install a package without error you have no fucking clue what system dependencies that package required and used, so no fucking clue to let people know about them.

It is the entire dependance issue with packages and frameworks, only everybody just decided its ok to only solve one layer but not the other.

**Comment by SpaceManiac** [comment]
It is completely outside of my power to fix the N distros * M programming languages problem, but I'll do a pass and make sure any system deps are at least documented.

**Comment by Cyberboss** [comment]
From the tg Docker which runs ubuntu xenial i386:

```
Step 14/15 : RUN ldd /root/.byond/bin/rust_g
 ---> Running in b1a2b0b8f67e
        linux-gate.so.1 =>  (0xf7719000)
        libssl.so.1.0.0 => /lib/i386-linux-gnu/libssl.so.1.0.0 (0xf762b000)
        libcrypto.so.1.0.0 => /lib/i386-linux-gnu/libcrypto.so.1.0.0 (0xf743e000)
        libdl.so.2 => /lib/i386-linux-gnu/libdl.so.2 (0xf7439000)
        librt.so.1 => /lib/i386-linux-gnu/librt.so.1 (0xf7430000)
        libpthread.so.0 => /lib/i386-linux-gnu/libpthread.so.0 (0xf7413000)
        libgcc_s.so.1 => /lib/i386-linux-gnu/libgcc_s.so.1 (0xf73f5000)
        libc.so.6 => /lib/i386-linux-gnu/libc.so.6 (0xf723f000)
        /lib/ld-linux.so.2 (0xf771a000)
        libm.so.6 => /lib/i386-linux-gnu/libm.so.6 (0xf71ea000)
```
