### ISSUE TITLE
Pull CI BYOND version from /tg/ repo

### ISSUE THREAD

**Issue by Cyberboss** [tgstation/rust-g#56]
https://github.com/tgstation/tgstation/blob/master/dependencies.sh

**Comment by ZeWaka** [comment]
Here's where to actually pull from: https://github.com/tgstation/tgstation/blob/master/Dockerfile

**Comment by Cyberboss** [comment]
I'd use the .sh because that's the "official" way of getting it. If I can ever figure out how to have the value there instead of the Dockerfile that will happen

**Comment by SpaceManiac** [comment]
fetching stuff from a remote is annoying and fragile when unnecessary, I'm okay with just updating it manually for now
