### ISSUE TITLE
Why is the Rust Analyzer target set to i686-pc-windows gnu?

### ISSUE THREAD

**Issue by ZeWaka** [tgstation/rust-g#86]
https://github.com/tgstation/rust-g/blob/274fb1836d83836d8b613cf300435d75870d7a1b/.vscode/settings.json#L2

Title, this has bothered contributors besides myself, who have to tell git to ignore our changes to make it the msvc target instead.

**Comment by Mothblocks** [comment]
Plz change this

**Comment by willox** [comment]
me too

**Comment by optimumtact** [comment]
as i've taken to calling it, gnu/windows
