### ISSUE TITLE
CI should generate rust_g.dm on default features

### ISSUE THREAD

**Issue by Mothblocks** [tgstation/rust-g#92]
It's really annoying to do this for releases

**Comment by optimumtact** [comment]
but then it won't test everything?

**Comment by Mothblocks** [comment]
I'm not sure what you mean, what I'm talking about is how I can already get rust_g.dll and librustg.so from artifacts, I want to be able to get rust_g.dm too

**Comment by optimumtact** [comment]
oh I misread this issue request entirely just ignore me
